[package]
name = "chronos"
version = "0.1.0"
authors = ["Chronium <onlivechronium@gmail.com>"]

[lib]
path = "kernel/lib.rs"
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[dependencies]
rlibc = "*"
cpuio = "*"
volatile = "*"
spin = "*"